---
kibana_version: "7.x"

kibana_package: kibana
kibana_package_state: present

kibana_service_state: started
kibana_service_enabled: true

kibana_config_template: kibana.yml.j2
kibana_config_file_path: /etc/kibana/kibana.yml

kibana_server_port: 5601
kibana_server_host: "10.0.5.91"

kibana_elasticsearch_url: "http://10.0.5.91:9200"
kibana_elasticsearch_username: "kibana"
kibana_elasticsearch_password: "kibana"
