- name: webmin SYS265
  hosts: wordpress
  become: true
  vars:
    install_utilities: false
    firewalld_enable: true
  roles:
  - roles/semuadmin.webmin

  tasks:
  - name: add firewall rule
    firewalld:
      port: 10000/tcp
      permanent: true
      state: enabled
