- name: install windows application
  hosts: windows
  tasks:
    - name: Install Firefox and 7Zip
      win_chocolatey:
        name:
        - firefox
        - 7zip
        - notepadplusplus
        state: present
